spring.application.name=delivery-service
server.port=8081

# The address where Docker is running Kafka
spring.kafka.producer.bootstrap-servers=localhost:9092

# Serializers tell Kafka how to turn your Java Strings into data it can store
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer